apiVersion: v1
kind: Service
metadata:
  name: adonis-kub-projeto
spec:
  selector:
    app: adonis-kub-projeto
  ports:
    - name: http
      protocol: TCP
      port: 3333
      targetPort: 3333
  type: LoadBalancer
